# frozen_string_literal: true

require "json"
require "socket"

module Ruact
  # ActionView helper module included in ActionView::Base via Railtie.
  # Provides the +__ruact_component__+ method that ERB templates call after the
  # preprocessor transforms PascalCase tags into +<%= __ruact_component__(...) %>+.
  #
  # Thread-safe: ActionView creates a fresh view context per request, so the
  # render context (set by Ruact::Controller#ruact_render on the controller as
  # +@ruact_render_context+ and copied to the view by Rails's view_assigns
  # plumbing — see Story 7.9 / Bug 7.8-B) is per-request — no shared state.
  module ViewHelper
    # Registers +name+ with +props+ in the per-render RenderContext (set by
    # Ruact::Controller#ruact_render on the controller as +@ruact_render_context+;
    # Rails copies it to the view via +_assigns_for_view_context+ because the
    # name does not match +DEFAULT_PROTECTED_INSTANCE_VARIABLES+'s +/\A@_/+
    # filter) and returns an HTML comment placeholder that HtmlConverter later
    # replaces with a ReactElement node.
    #
    # The returned string MUST be html_safe so ActionView does not escape the
    # angle brackets — if it were escaped, HtmlConverter would not find the
    # placeholder in the HTML output.
    def __ruact_component__(name, props = {})
      ctx = @ruact_render_context
      raise Ruact::Error, "ruact: __ruact_component__ called outside a ruact_render flow" if ctx.nil?

      token = ctx.register(name, props)
      "<!-- #{token} -->".html_safe
    end

    # Story 14.2 (FR104) — emits ruact's full JavaScript asset block: the
    # dev/prod bootstrap entry `<script>` tags (re-targeting the virtual entry
    # `virtual:ruact/bootstrap` — in dev the react-refresh preamble + `@vite/client`
    # + the bootstrap module; in prod the hashed URL read from the Vite manifest)
    # AND, when a Flight payload is given, the `__FLIGHT_DATA` inline bootstrap
    # `<script>` the entry reads on boot.
    #
    # This is the SINGLE implementation of the JS asset markup —
    # `Ruact::Controller#ruact_html_shell` delegates to it so the controller's
    # generated shell and any view that calls the helper emit byte-identical tags
    # (no drift). Available in every view via the railtie's
    # `ActionView::Base.include(Ruact::ViewHelper)`.
    #
    # @param flight_payload [String, nil] the per-render Flight wire payload to
    #   inline as `__FLIGHT_DATA`; omit (or pass nil) to emit only the entry tags.
    # @return [ActiveSupport::SafeBuffer] the asset markup, html_safe
    # @example In a layout
    #   <%= ruact_js_assets %>
    def ruact_js_assets(flight_payload = nil)
      parts = []
      parts << ruact_flight_data_script(flight_payload) unless flight_payload.nil?
      parts << ruact_vite_tags
      parts.join("\n").html_safe
    end

    private

    # The `__FLIGHT_DATA` inline bootstrap `<script>` — pushes the per-render
    # Flight payload onto the global queue the bootstrap entry drains on boot.
    # `</script>` in the payload is escaped to prevent an HTML/XSS breakout
    # (mandatory whenever Flight data is inlined into a `<script>` tag).
    def ruact_flight_data_script(flight_payload)
      escaped_payload = flight_payload.gsub("</script>", '<\/script>')
      <<~HTML.strip
        <script>
          (function() {
            var d = (self.__FLIGHT_DATA = self.__FLIGHT_DATA || []);
            d.push(#{escaped_payload.inspect});
          })();
        </script>
      HTML
    end

    # The bootstrap entry `<script>` tags — dev serves the virtual module from
    # the Vite dev server (with the react-refresh preamble + `@vite/client`);
    # prod reads the hashed URL from the Vite manifest. Both target the SAME
    # virtual entry id (`Ruact.bootstrap_virtual_id`) so dev/prod stay in lockstep.
    def ruact_vite_tags
      if Rails.env.development? && vite_dev_running?
        # @vitejs/plugin-react normally injects this preamble by processing index.html.
        # Since our HTML is generated by Rails (not Vite), we inject it manually.
        # Without it, every JSX file throws "can't detect preamble" at runtime.
        dev_server = Ruact.config.vite_dev_server.chomp("/")
        react_preamble = <<~JS
          <script type="module">
            import RefreshRuntime from '#{dev_server}/@react-refresh';
            RefreshRuntime.injectIntoGlobalHook(window);
            window.$RefreshReg$ = () => {};
            window.$RefreshSig$ = () => (type) => type;
            window.__vite_plugin_react_preamble_installed__ = true;
          </script>
        JS

        react_preamble + <<~HTML
          <script type="module" src="#{dev_server}/@vite/client"></script>
          <script type="module" src="#{ruact_bootstrap_dev_url}"></script>
        HTML
      else
        # Production: read the hashed URL from the Vite manifest, keyed on the
        # virtual entry id (the manifest key Vite emits for the virtual input).
        entry = vite_manifest_entry(Ruact.bootstrap_virtual_id)
        src   = entry ? "/assets/#{entry['file']}" : "/assets/application.js"
        %(<script type="module" src="#{src}"></script>)
      end
    end

    # The Vite dev-server URL for the virtual bootstrap. Vite serves virtual
    # modules under `/@id/`, encoding the resolved id's leading NUL (`\0`) as
    # `__x00__` — so `\0virtual:ruact/bootstrap` is served at
    # `/@id/__x00__virtual:ruact/bootstrap`. A plain `/virtual:...` URL falls
    # through to the dev server's HTML fallback, so this encoding is required.
    def ruact_bootstrap_dev_url
      "#{Ruact.config.vite_dev_server.chomp('/')}/@id/__x00__#{Ruact.bootstrap_virtual_id}"
    end

    # Probe the CONFIGURED dev server (host:port parsed from
    # `Ruact.config.vite_dev_server`), not a hardcoded localhost:5173 — so a
    # custom `vite_dev_server` and the emitted dev `<script>` URLs always agree
    # on whether the server is up.
    def vite_dev_running?
      require "socket"
      require "uri"
      uri = URI.parse(Ruact.config.vite_dev_server)
      Socket.tcp(uri.host || "localhost", uri.port || 5173, connect_timeout: 1).close
      true
    rescue Errno::ECONNREFUSED, Errno::EHOSTUNREACH, Errno::ETIMEDOUT, SocketError
      false
    end

    def vite_manifest_entry(src_path)
      manifest_path = Rails.root.join("public", "assets", ".vite", "manifest.json")
      return nil unless File.exist?(manifest_path)

      JSON.parse(File.read(manifest_path))[src_path]
    end
  end
end
