// AUTO-GENERATED by vite-plugin-ruact (Story 9.3). DO NOT EDIT.
// Source: Rails route table (version 2)
// Generated at: 2026-06-09T21:41:02Z
import { _makeServerFunction } from "ruact/server-functions-runtime";

// (no server functions exposed yet — add a non-GET route on a Ruact::Server controller)
void _makeServerFunction;

export { revalidate } from "ruact/server-functions-runtime";
