# frozen_string_literal: true

module Ruact
  module ServerFunctions
    # Renders the snapshot Hash into the TypeScript module emitted to
    # `app/javascript/.ruact/server-functions.ts`. Pure string-building plus a
    # single write-if-changed call.
    #
    # The output of {.render} MUST be byte-identical to the JS-side codegen in
    # `gem/vendor/javascript/vite-plugin-ruact/server-functions-codegen.mjs`.
    # The cross-implementation parity test under
    # `gem/vendor/javascript/vite-plugin-ruact/server-functions-codegen.test.mjs`
    # asserts this invariant; if it fails, fix the offending side rather than
    # normalizing in the assertion (Story 8.0a Task 8.5).
    module Codegen
      # Bumped only when the rendered shape changes. Used by tests to assert
      # cross-implementation parity without coupling to the literal byte string.
      VERSION = 1

      RUNTIME_IMPORT = '"ruact/server-functions-runtime"'

      ACTION_SIGNATURE = "(args?: Record<string, unknown>) => Promise<unknown>"
      QUERY_SIGNATURE  = "() => Promise<unknown>"

      class << self
        # Renders +snapshot+ into the TS module text. Pure; no I/O.
        #
        # @param snapshot [Hash] result of {Ruact::ServerFunctions::Snapshot.dump};
        #   must contain `:version`, `:generated_at`, `:functions` (with string-keyed
        #   entries).
        # @return [String] TS module bytes, terminated by a single trailing newline.
        def render(snapshot)
          version      = snapshot.fetch(:version) { snapshot.fetch("version") }
          generated_at = snapshot.fetch(:generated_at) { snapshot.fetch("generated_at") }
          functions    = snapshot.fetch(:functions) { snapshot.fetch("functions") }

          io = +""
          io << "// AUTO-GENERATED by vite-plugin-ruact (Story 8.0a). DO NOT EDIT.\n"
          io << "// Source: tmp/cache/ruact/server-functions.json (version #{version})\n"
          io << "// Generated at: #{generated_at}\n"
          io << "import { _makeRef } from #{RUNTIME_IMPORT};\n"

          if functions.empty?
            io << "\n// (no server functions registered)\n"
          else
            io << "\n"
            functions.each do |fn|
              io << render_export(fn)
            end
          end

          io
        end

        # Writes the rendered TS module to +output_path+, only if it changed.
        # See {Ruact::ServerFunctions::SnapshotWriter.write_if_changed!}.
        #
        # @param snapshot [Hash]
        # @param output_path [String, Pathname]
        # @return [Boolean] true if the file was written; false if unchanged.
        def generate_ts!(snapshot:, output_path:)
          SnapshotWriter.write_if_changed!(path: output_path, content: render(snapshot))
        end

        private

        def render_export(entry)
          js_id     = entry["js_identifier"] || entry[:js_identifier]
          kind      = (entry["kind"] || entry[:kind]).to_s
          ruby_sym  = entry["ruby_symbol"] || entry[:ruby_symbol]
          signature = kind == "query" ? QUERY_SIGNATURE : ACTION_SIGNATURE

          "export const #{js_id}: #{signature} =\n  _makeRef(\"#{ruby_sym}\");\n"
        end
      end
    end
  end
end
