# frozen_string_literal: true

require "json"
require "ruact/server_functions/name_bridge"

module Ruact
  module ServerFunctions
    module Codegen
      # Story 9.3 — renders a version-2 (route-driven) snapshot into the TS
      # module. Each entry is an action targeting a real path + verb, emitted as
      # `_makeServerFunction({ method, path, segments })` instead of v1's
      # `_makeRef("<sym>")`. Lives in its own module (nested in {Codegen}) so the
      # v1 singleton class stays within its size budget; {Codegen.render}
      # delegates here when `snapshot.version == 2`.
      #
      # The output MUST stay byte-identical to the JS-side `renderV2` in
      # `gem/vendor/javascript/vite-plugin-ruact/server-functions-codegen.mjs`;
      # the parity test ("Story 9.3 — route-driven (v2) render + parity") asserts
      # this. Constants (ACTION_SIGNATURE, RUNTIME_IMPORT, REVALIDATE_REEXPORT,
      # LINE_TERMINATORS, VALID_JS_IDENTIFIER) are reused from {Codegen} via
      # lexical scope.
      module V2
        # Verbs a v2 entry may carry (mirrors {RouteSource::MUTATION_VERBS}).
        HTTP_METHODS = %w[POST PUT PATCH DELETE].to_set.freeze

        class << self
          # @param version [Integer, String]
          # @param generated_at [String]
          # @param functions [Array<Hash>] route-derived entries.
          # @return [String] TS module bytes (single trailing newline).
          # @raise [Ruact::ConfigurationError] on any trust-boundary violation.
          def render(version, generated_at, functions)
            validate_functions!(functions)

            io = +""
            io << "// AUTO-GENERATED by vite-plugin-ruact (Story 9.3). DO NOT EDIT.\n"
            io << "// Source: Rails route table (version #{version})\n"
            io << "// Generated at: #{generated_at}\n"
            io << "import { _makeServerFunction } from #{RUNTIME_IMPORT};\n"

            if functions.empty?
              io << "\n// (no server functions exposed yet — add a non-GET route on a Ruact::Server controller)\n"
              io << "void _makeServerFunction;\n"
            else
              io << "\n"
              functions.each { |entry| io << render_export(entry) }
            end

            io << "\n"
            io << REVALIDATE_REEXPORT
            io
          end

          private

          def render_export(entry)
            js_id = fetch(entry, "js_identifier")
            method = fetch(entry, "http_method")
            path = fetch(entry, "path")
            segments = fetch(entry, "segments") || []

            descriptor =
              "{ method: #{JSON.dump(method)}, path: #{JSON.dump(path)}, " \
              "segments: [#{segments.map { |s| JSON.dump(s) }.join(', ')}] }"

            "export const #{js_id}: #{ACTION_SIGNATURE} =\n  _makeServerFunction(#{descriptor});\n"
          end

          def validate_functions!(functions)
            unless functions.is_a?(Array)
              raise Ruact::ConfigurationError,
                    "ruact server-function codegen: snapshot.functions must be an Array, got #{functions.class}"
            end

            seen = {}
            functions.each { |entry| validate_entry!(entry, seen) }
          end

          def validate_entry!(entry, seen)
            unless entry.is_a?(Hash)
              raise Ruact::ConfigurationError,
                    "ruact server-function codegen: snapshot.functions entry is not a Hash: #{entry.inspect}"
            end

            js_id = fetch(entry, "js_identifier")
            validate_identifier!(js_id, seen)
            validate_kind!(js_id, fetch(entry, "kind").to_s)
            validate_method!(js_id, fetch(entry, "http_method"))
            path = fetch(entry, "path")
            validate_path!(js_id, path)
            validate_segments!(js_id, path, fetch(entry, "segments"))
            seen[js_id] = true
          end

          def validate_identifier!(js_id, seen)
            unless js_id.is_a?(String) && js_id.match?(VALID_JS_IDENTIFIER)
              raise Ruact::ConfigurationError,
                    "ruact server-function codegen rejected a v2 snapshot entry: " \
                    "js_identifier=#{js_id.inspect} is not a valid JS identifier " \
                    "(must match #{VALID_JS_IDENTIFIER.inspect}); snapshot JSON is corrupted."
            end
            if NameBridge::RESERVED_JS_IDENTIFIERS.include?(js_id) ||
               NameBridge::RESERVED_BY_RUACT.include?(js_id)
              raise Ruact::ConfigurationError,
                    "ruact server-function codegen: js_identifier #{js_id.inspect} is reserved — " \
                    "cannot be exported; snapshot JSON is corrupted."
            end
            return unless seen.key?(js_id)

            raise Ruact::ConfigurationError,
                  "ruact server-function codegen: duplicate js_identifier #{js_id.inspect} in snapshot."
          end

          def validate_kind!(js_id, kind)
            return if kind == "action"

            raise Ruact::ConfigurationError,
                  "ruact server-function codegen: v2 snapshot entry #{js_id.inspect} has invalid " \
                  "kind #{kind.inspect} (v2 entries are always \"action\")."
          end

          def validate_method!(js_id, method)
            return if HTTP_METHODS.include?(method)

            raise Ruact::ConfigurationError,
                  "ruact server-function codegen: v2 snapshot entry #{js_id.inspect} has invalid " \
                  "http_method #{method.inspect} (must be one of #{HTTP_METHODS.to_a.inspect})."
          end

          def validate_path!(js_id, path)
            unless path.is_a?(String) && path.start_with?("/")
              raise Ruact::ConfigurationError,
                    "ruact server-function codegen: v2 snapshot entry #{js_id.inspect} has invalid " \
                    "path #{path.inspect} (must be a String beginning with \"/\")."
            end
            return unless path.match?(LINE_TERMINATORS)

            raise Ruact::ConfigurationError,
                  "ruact server-function codegen: v2 snapshot entry #{js_id.inspect} path contains a " \
                  "line break — would break out of the generated call; snapshot JSON is corrupted."
          end

          def validate_segments!(js_id, path, segments)
            unless segments.is_a?(Array) && segments.all? { |s| s.is_a?(String) && !s.empty? }
              raise Ruact::ConfigurationError,
                    "ruact server-function codegen: v2 snapshot entry #{js_id.inspect} has invalid " \
                    "segments #{segments.inspect} (must be an Array of non-empty Strings)."
            end
            # Whole-token match: `:id` must NOT satisfy a declared segment when
            # the path only has `:id_extra` (a substring `include?` would).
            missing = segments.reject { |s| path.match?(/:#{Regexp.escape(s)}(?![A-Za-z0-9_])/) }
            return if missing.empty?

            raise Ruact::ConfigurationError,
                  "ruact server-function codegen: v2 snapshot entry #{js_id.inspect} declares " \
                  "segment(s) #{missing.inspect} absent from path #{path.inspect}; snapshot JSON is corrupted."
          end

          # v2 snapshots use string keys on disk; specs may pass symbol keys.
          def fetch(entry, key)
            entry[key] || entry[key.to_sym]
          end
        end
      end
    end
  end
end
