# frozen_string_literal: true

require "json"
require "ruact/server_functions/name_bridge"

module Ruact
  module ServerFunctions
    module Codegen
      # Story 9.3 — renders a version-2 (route-driven) snapshot into the TS
      # module. Each entry is an action targeting a real path + verb, emitted as
      # `_makeServerFunction({ method, path, segments })` instead of v1's
      # `_makeRef("<sym>")`. Lives in its own module (nested in {Codegen}) so the
      # v1 singleton class stays within its size budget; {Codegen.render}
      # delegates here when `snapshot.version == 2`.
      #
      # The output MUST stay byte-identical to the JS-side `renderV2` in
      # `gem/vendor/javascript/vite-plugin-ruact/server-functions-codegen.mjs`;
      # the parity test ("Story 9.3 — route-driven (v2) render + parity") asserts
      # this. Constants (ACTION_SIGNATURE, RUNTIME_IMPORT, REVALIDATE_REEXPORT,
      # LINE_TERMINATORS, VALID_JS_IDENTIFIER) are reused from {Codegen} via
      # lexical scope.
      module V2
        # Verbs a v2 ACTION entry may carry (mirrors {RouteSource::MUTATION_VERBS}).
        HTTP_METHODS = %w[POST PUT PATCH DELETE].to_set.freeze

        # Story 9.5 — the verb a v2 QUERY entry may carry. Queries are reads,
        # mounted by {Ruact::Routing#ruact_queries} as named GET routes; the
        # 2026-06-02 ADR addendum restored HTTP GET semantics for queries, so a
        # query entry is GET-only.
        QUERY_HTTP_METHODS = %w[GET].to_set.freeze

        class << self
          # @param version [Integer, String]
          # @param generated_at [String]
          # @param functions [Array<Hash>] route-derived entries (actions AND,
          #   Story 9.5, queries).
          # @return [String] TS module bytes (single trailing newline).
          # @raise [Ruact::ConfigurationError] on any trust-boundary violation.
          def render(version, generated_at, functions)
            validate_functions!(functions)

            has_query  = functions.any? { |entry| fetch(entry, "kind").to_s == "query" }
            has_action = functions.any? { |entry| fetch(entry, "kind").to_s == "action" }

            # Import only what is used. Keep `_makeServerFunction` in the empty
            # case so the no-functions module stays byte-identical to Story 9.3.
            imports = []
            imports << "_makeServerFunction" if has_action || functions.empty?
            imports << "_makeQuery" if has_query

            io = +""
            io << "// AUTO-GENERATED by vite-plugin-ruact (Story 9.3). DO NOT EDIT.\n"
            io << "// Source: Rails route table (version #{version})\n"
            io << "// Generated at: #{generated_at}\n"
            io << "import { #{imports.join(', ')} } from #{RUNTIME_IMPORT};\n"

            if functions.empty?
              io << "\n// (no server functions exposed yet — add a non-GET route on a Ruact::Server controller)\n"
              io << "void _makeServerFunction;\n"
            else
              io << "\n"
              functions.each { |entry| io << render_export(entry) }
            end

            io << "\n"
            io << REVALIDATE_REEXPORT
            io << USEQUERY_REEXPORT if has_query
            io
          end

          private

          def render_export(entry)
            return render_query_export(entry) if fetch(entry, "kind").to_s == "query"

            js_id = fetch(entry, "js_identifier")
            method = fetch(entry, "http_method")
            path = fetch(entry, "path")
            segments = fetch(entry, "segments") || []

            descriptor =
              "{ method: #{JSON.dump(method)}, path: #{JSON.dump(path)}, " \
              "segments: [#{segments.map { |s| JSON.dump(s) }.join(', ')}] }"

            "export const #{js_id}: #{ACTION_SIGNATURE} =\n  _makeServerFunction(#{descriptor});\n"
          end

          # Story 9.5 — a query export binds a `_makeQuery` accessor carrying
          # its GET descriptor `{ path, kind: "query" }`. `useQuery(<id>, …)`
          # consumes it — reads go to `GET /q/<jsId>`. The signature accepts
          # params only when the query method declares kwargs (FR88).
          def render_query_export(entry)
            js_id = fetch(entry, "js_identifier")
            path = fetch(entry, "path")
            signature = fetch(entry, "accepts_params") ? QUERY_PARAMS_SIGNATURE : QUERY_SIGNATURE

            descriptor = "{ path: #{JSON.dump(path)}, kind: \"query\" }"
            "export const #{js_id}: #{signature} =\n  _makeQuery(#{descriptor});\n"
          end

          def validate_functions!(functions)
            unless functions.is_a?(Array)
              raise Ruact::ConfigurationError,
                    "ruact server-function codegen: snapshot.functions must be an Array, got #{functions.class}"
            end

            seen = {}
            functions.each { |entry| validate_entry!(entry, seen) }
          end

          def validate_entry!(entry, seen)
            unless entry.is_a?(Hash)
              raise Ruact::ConfigurationError,
                    "ruact server-function codegen: snapshot.functions entry is not a Hash: #{entry.inspect}"
            end

            js_id = fetch(entry, "js_identifier")
            validate_identifier!(js_id, seen)
            kind = fetch(entry, "kind").to_s
            validate_kind!(js_id, kind)
            validate_method!(js_id, kind, fetch(entry, "http_method"))
            path = fetch(entry, "path")
            validate_path!(js_id, path)
            validate_segments!(js_id, path, fetch(entry, "segments"))
            seen[js_id] = true
          end

          def validate_identifier!(js_id, seen)
            unless js_id.is_a?(String) && js_id.match?(VALID_JS_IDENTIFIER)
              raise Ruact::ConfigurationError,
                    "ruact server-function codegen rejected a v2 snapshot entry: " \
                    "js_identifier=#{js_id.inspect} is not a valid JS identifier " \
                    "(must match #{VALID_JS_IDENTIFIER.inspect}); snapshot JSON is corrupted."
            end
            if NameBridge::RESERVED_JS_IDENTIFIERS.include?(js_id) ||
               NameBridge::RESERVED_BY_RUACT.include?(js_id)
              raise Ruact::ConfigurationError,
                    "ruact server-function codegen: js_identifier #{js_id.inspect} is reserved — " \
                    "cannot be exported; snapshot JSON is corrupted."
            end
            return unless seen.key?(js_id)

            raise Ruact::ConfigurationError,
                  "ruact server-function codegen: duplicate js_identifier #{js_id.inspect} in snapshot."
          end

          def validate_kind!(js_id, kind)
            return if %w[action query].include?(kind)

            raise Ruact::ConfigurationError,
                  "ruact server-function codegen: v2 snapshot entry #{js_id.inspect} has invalid " \
                  "kind #{kind.inspect} (v2 entries are \"action\" or \"query\")."
          end

          # Story 9.5 — actions carry a mutation verb; queries are GET-only.
          def validate_method!(js_id, kind, method)
            allowed = kind == "query" ? QUERY_HTTP_METHODS : HTTP_METHODS
            return if allowed.include?(method)

            raise Ruact::ConfigurationError,
                  "ruact server-function codegen: v2 snapshot entry #{js_id.inspect} has invalid " \
                  "http_method #{method.inspect} (must be one of #{allowed.to_a.inspect})."
          end

          def validate_path!(js_id, path)
            unless path.is_a?(String) && path.start_with?("/")
              raise Ruact::ConfigurationError,
                    "ruact server-function codegen: v2 snapshot entry #{js_id.inspect} has invalid " \
                    "path #{path.inspect} (must be a String beginning with \"/\")."
            end
            return unless path.match?(LINE_TERMINATORS)

            raise Ruact::ConfigurationError,
                  "ruact server-function codegen: v2 snapshot entry #{js_id.inspect} path contains a " \
                  "line break — would break out of the generated call; snapshot JSON is corrupted."
          end

          def validate_segments!(js_id, path, segments)
            unless segments.is_a?(Array) && segments.all? { |s| s.is_a?(String) && !s.empty? }
              raise Ruact::ConfigurationError,
                    "ruact server-function codegen: v2 snapshot entry #{js_id.inspect} has invalid " \
                    "segments #{segments.inspect} (must be an Array of non-empty Strings)."
            end
            # Whole-token match: `:id` must NOT satisfy a declared segment when
            # the path only has `:id_extra` (a substring `include?` would).
            missing = segments.reject { |s| path.match?(/:#{Regexp.escape(s)}(?![A-Za-z0-9_])/) }
            unless missing.empty?
              raise Ruact::ConfigurationError,
                    "ruact server-function codegen: v2 snapshot entry #{js_id.inspect} declares " \
                    "segment(s) #{missing.inspect} absent from path #{path.inspect}; snapshot JSON is corrupted."
            end

            # Bidirectional: every dynamic `:param` in the path MUST be declared
            # in segments, else the runtime would fetch a literal `:param` URL.
            undeclared = path.scan(/:([A-Za-z_][A-Za-z0-9_]*)/).flatten - segments
            return if undeclared.empty?

            raise Ruact::ConfigurationError,
                  "ruact server-function codegen: v2 snapshot entry #{js_id.inspect} path #{path.inspect} " \
                  "has dynamic segment(s) #{undeclared.inspect} not declared in segments; snapshot JSON is corrupted."
          end

          # v2 snapshots use string keys on disk; specs may pass symbol keys.
          def fetch(entry, key)
            entry[key] || entry[key.to_sym]
          end
        end
      end
    end
  end
end
