# frozen_string_literal: true

require "spec_helper"
require "tmpdir"

module Ruact
  module ServerFunctions
    RSpec.describe Codegen, :story_9_3 do
      # Story 9.9 — the v1 (registry / `_makeRef`) render path was demolished;
      # only the route-driven (version-2) snapshot is supported.
      let(:v2_base) do
        {
          version: 2,
          generated_at: "2026-06-09T00:00:00Z",
          functions: []
        }
      end

      describe ".render — unsupported / malformed snapshots" do
        it "rejects when snapshot is not a Hash" do
          expect { described_class.render("oops") }
            .to raise_error(Ruact::ConfigurationError, /snapshot must be a Hash/)
        end

        it "wraps a missing root key as Ruact::ConfigurationError" do
          evil = { generated_at: "2026-05-14T00:00:00Z", functions: [] } # no :version
          expect { described_class.render(evil) }
            .to raise_error(Ruact::ConfigurationError, /missing required key/)
        end

        it "rejects a snapshot whose version contains a line break" do
          evil = v2_base.merge(version: "2\n// injected")
          expect { described_class.render(evil) }
            .to raise_error(Ruact::ConfigurationError, /version.*line break/)
        end

        it "rejects a snapshot whose generated_at contains a line break" do
          evil = v2_base.merge(generated_at: "2026-05-14\n// injected")
          expect { described_class.render(evil) }
            .to raise_error(Ruact::ConfigurationError, /generated_at.*line break/)
        end

        it "rejects a snapshot whose version contains a U+2028 line separator (JS LineTerminator parity)" do
          evil = v2_base.merge(version: "2 // injected")
          expect { described_class.render(evil) }
            .to raise_error(Ruact::ConfigurationError, /line break.*U\+2028/)
        end

        it "rejects a snapshot whose generated_at contains a U+2029 paragraph separator (JS LineTerminator parity)" do
          evil = v2_base.merge(generated_at: "2026-05-14 // injected")
          expect { described_class.render(evil) }
            .to raise_error(Ruact::ConfigurationError, /line break.*U\+2029/)
        end

        it "rejects an unsupported (non-v2) snapshot version" do
          evil = v2_base.merge(version: 1)
          expect { described_class.render(evil) }
            .to raise_error(Ruact::ConfigurationError, /unsupported snapshot version/)
        end
      end

      describe ".generate_ts! (write-if-changed wrapper)" do
        around do |example|
          Dir.mktmpdir do |dir|
            @tmpdir = dir
            example.run
          end
        end

        let(:path) { File.join(@tmpdir, "server-functions.ts") }

        it "writes the file on first call and returns true" do
          expect(described_class.generate_ts!(snapshot: v2_base, output_path: path))
            .to be(true)
          expect(File.read(path)).to include("// AUTO-GENERATED by vite-plugin-ruact")
        end

        it "does NOT rewrite when the content is byte-identical" do
          described_class.generate_ts!(snapshot: v2_base, output_path: path)
          expect(described_class.generate_ts!(snapshot: v2_base, output_path: path))
            .to be(false)
        end
      end

      describe ".render — route-driven v2 snapshot (Story 9.3)", :story_9_3 do
        let(:v2_snapshot) do
          {
            version: 2,
            generated_at: "2026-06-09T00:00:00Z",
            functions: [
              { "js_identifier" => "createPost", "kind" => "action",
                "http_method" => "POST", "path" => "/posts", "segments" => [],
                "controller" => "posts", "action" => "create" },
              { "js_identifier" => "updatePost", "kind" => "action",
                "http_method" => "PATCH", "path" => "/posts/:id", "segments" => ["id"],
                "controller" => "posts", "action" => "update" }
            ]
          }
        end

        it "dispatches on version 2 and emits _makeServerFunction with real path+verb" do
          out = described_class.render(v2_snapshot)
          expect(out).to include('import { _makeServerFunction } from "ruact/server-functions-runtime";')
          expect(out).to include('_makeServerFunction({ method: "POST", path: "/posts", segments: [] });')
          expect(out).to include('_makeServerFunction({ method: "PATCH", path: "/posts/:id", segments: ["id"] });')
          expect(out).to include('export { revalidate } from "ruact/server-functions-runtime";')
        end

        it "keeps the Story 8.2 intersection signature on v2 actions (form action support)" do
          out = described_class.render(v2_snapshot)
          expect(out).to include("& ((formData: FormData) => Promise<void>)")
        end

        it "emits the empty-v2 module when no routes are exposed" do
          out = described_class.render(version: 2, generated_at: "2026-06-09T00:00:00Z", functions: [])
          expect(out).to include("void _makeServerFunction;")
          expect(out).to include("(no server functions exposed yet")
          expect(out).to end_with("export { revalidate } from \"ruact/server-functions-runtime\";\n")
        end

        it "rejects a v2 entry with an invalid http_method" do
          evil = v2_snapshot.merge(functions: [
                                     { "js_identifier" => "createPost", "kind" => "action",
                                       "http_method" => "GET", "path" => "/posts", "segments" => [] }
                                   ])
          expect { described_class.render(evil) }
            .to raise_error(Ruact::ConfigurationError, /invalid http_method/)
        end

        it "rejects a v2 entry declaring a segment absent from the path" do
          evil = v2_snapshot.merge(functions: [
                                     { "js_identifier" => "updatePost", "kind" => "action",
                                       "http_method" => "PATCH", "path" => "/posts", "segments" => ["id"] }
                                   ])
          expect { described_class.render(evil) }
            .to raise_error(Ruact::ConfigurationError, /absent from path/)
        end

        it "rejects a v2 entry with an unknown kind (Story 9.5 — action/query only)" do
          evil = v2_snapshot.merge(functions: [
                                     { "js_identifier" => "createPost", "kind" => "mutation",
                                       "http_method" => "POST", "path" => "/posts", "segments" => [] }
                                   ])
          expect { described_class.render(evil) }
            .to raise_error(Ruact::ConfigurationError, /v2 entries are "action" or "query"/)
        end

        it "rejects a v2 entry whose js_identifier is reserved" do
          evil = v2_snapshot.merge(functions: [
                                     { "js_identifier" => "revalidate", "kind" => "action",
                                       "http_method" => "POST", "path" => "/posts", "segments" => [] }
                                   ])
          expect { described_class.render(evil) }
            .to raise_error(Ruact::ConfigurationError, /reserved/)
        end

        it "rejects a v2 entry named after the v2 runtime accessor (_makeServerFunction)" do
          evil = v2_snapshot.merge(functions: [
                                     { "js_identifier" => "_makeServerFunction", "kind" => "action",
                                       "http_method" => "POST", "path" => "/posts", "segments" => [] }
                                   ])
          expect { described_class.render(evil) }
            .to raise_error(Ruact::ConfigurationError, /reserved/)
        end

        it "rejects a v2 path with an undeclared dynamic segment (bidirectional guard)" do
          evil = v2_snapshot.merge(functions: [
                                     { "js_identifier" => "updatePost", "kind" => "action",
                                       "http_method" => "PATCH", "path" => "/posts/:id",
                                       "segments" => [] }
                                   ])
          expect { described_class.render(evil) }
            .to raise_error(Ruact::ConfigurationError, /not declared in segments/)
        end

        it "rejects a v2 segment that only substring-matches a longer path token" do
          evil = v2_snapshot.merge(functions: [
                                     { "js_identifier" => "updatePost", "kind" => "action",
                                       "http_method" => "PATCH", "path" => "/posts/:id_extra",
                                       "segments" => ["id"] }
                                   ])
          expect { described_class.render(evil) }
            .to raise_error(Ruact::ConfigurationError, /absent from path/)
        end
      end

      describe ".render — v2 query entries (Story 9.5)", :story_9_5 do
        def query_entry(js_id, path, accepts_params:)
          {
            "js_identifier" => js_id, "kind" => "query", "http_method" => "GET",
            "path" => path, "segments" => [], "accepts_params" => accepts_params,
            "controller" => "CatalogQuery", "action" => js_id
          }
        end

        it "emits a no-param query as _makeQuery with the () signature + useQuery re-export" do
          out = described_class.render(version: 2, generated_at: "t", functions: [
                                         query_entry("categories", "/q/categories", accepts_params: false)
                                       ])
          expect(out).to include('import { _makeQuery } from "ruact/server-functions-runtime";')
          expect(out).to include("export const categories: () => Promise<unknown> =")
          expect(out).to include('_makeQuery({ path: "/q/categories", kind: "query" });')
          expect(out).to include('export { useQuery } from "ruact/server-functions-runtime";')
          expect(out).to include('export { revalidate } from "ruact/server-functions-runtime";')
        end

        it "emits a param-declaring query with the (params) signature" do
          out = described_class.render(version: 2, generated_at: "t", functions: [
                                         query_entry("searchUsers", "/q/searchUsers", accepts_params: true)
                                       ])
          expect(out).to include("export const searchUsers: (params: Record<string, unknown>) => Promise<unknown> =")
          expect(out).to include('_makeQuery({ path: "/q/searchUsers", kind: "query" });')
        end

        it "imports both accessors and re-exports useQuery for a mixed action+query snapshot" do
          out = described_class.render(version: 2, generated_at: "t", functions: [
                                         { "js_identifier" => "createPost", "kind" => "action",
                                           "http_method" => "POST", "path" => "/posts", "segments" => [] },
                                         query_entry("categories", "/q/categories", accepts_params: false)
                                       ])
          expect(out).to include('import { _makeServerFunction, _makeQuery } from "ruact/server-functions-runtime";')
          expect(out).to include("_makeServerFunction({ method: \"POST\"")
          expect(out).to include("_makeQuery({ path: \"/q/categories\", kind: \"query\" })")
          expect(out).to include('export { useQuery } from "ruact/server-functions-runtime";')
        end

        it "accepts GET for a query entry (queries are GET-only)" do
          expect do
            described_class.render(version: 2, generated_at: "t", functions: [
                                     query_entry("categories", "/q/categories", accepts_params: false)
                                   ])
          end.not_to raise_error
        end

        it "rejects a non-GET verb on a query entry" do
          evil = { "js_identifier" => "categories", "kind" => "query", "http_method" => "POST",
                   "path" => "/q/categories", "segments" => [] }
          expect { described_class.render(version: 2, generated_at: "t", functions: [evil]) }
            .to raise_error(Ruact::ConfigurationError, /invalid http_method/)
        end

        it "rejects a query entry whose js_identifier is the useQuery re-export name" do
          evil = { "js_identifier" => "useQuery", "kind" => "query", "http_method" => "GET",
                   "path" => "/q/useQuery", "segments" => [], "accepts_params" => false }
          expect { described_class.render(version: 2, generated_at: "t", functions: [evil]) }
            .to raise_error(Ruact::ConfigurationError, /reserved/)
        end

        it "rejects a query entry whose js_identifier is the _makeQuery import name" do
          evil = { "js_identifier" => "_makeQuery", "kind" => "query", "http_method" => "GET",
                   "path" => "/q/_makeQuery", "segments" => [], "accepts_params" => false }
          expect { described_class.render(version: 2, generated_at: "t", functions: [evil]) }
            .to raise_error(Ruact::ConfigurationError, /reserved/)
        end

        it "does NOT re-export useQuery for an action-only snapshot (byte-stable with 9.3)" do
          out = described_class.render(version: 2, generated_at: "t", functions: [
                                         { "js_identifier" => "createPost", "kind" => "action",
                                           "http_method" => "POST", "path" => "/posts", "segments" => [] }
                                       ])
          expect(out).not_to include("useQuery")
          expect(out).to end_with("export { revalidate } from \"ruact/server-functions-runtime\";\n")
        end
      end
    end
  end
end
