# frozen_string_literal: true

require "spec_helper"
require "rake"
require "tmpdir"
require "fileutils"
require "action_controller"
require "ruact/server"

# Story 9.9 — exercises `rake ruact:server_functions:generate` end-to-end. The
# task forces the route table to load, then writes the route-driven (v2)
# snapshot to the REAL bridge (tmp/cache/ruact/server-functions.json) and
# renders the TS module. It runs against a tmpdir as Rails.root with a stubbed
# Rails.application providing a route set + a no-op routes_reloader.
module Ruact
  module ServerFunctions
    RSpec.describe "rake ruact:server_functions:generate", :story_9_9 do
      before do
        stub_const("RakeDemoPostsController", Class.new(ActionController::Base) { include Ruact::Server })
        reloader = Object.new
        def reloader.execute_unless_loaded; end
        rs = ActionDispatch::Routing::RouteSet.new
        rs.draw { resources :rake_demo_posts, only: %i[create update destroy] }
        app = Object.new
        app.define_singleton_method(:routes) { rs }
        app.define_singleton_method(:routes_reloader) { reloader }
        allow(Rails).to receive(:application).and_return(app)
      end

      around do |example|
        Dir.mktmpdir do |dir|
          original_root = Rails.root
          Rails.root    = Pathname.new(dir)
          @tmpdir       = dir

          prev = Rake.application
          Rake.application = Rake::Application.new
          Rake.application.define_task(Rake::Task, :environment)
          load File.expand_path("../../../lib/tasks/ruact.rake", __dir__)

          example.run
        ensure
          Rake.application = prev
          Rails.root       = original_root
        end
      end

      let(:json_path) { File.join(@tmpdir, "tmp/cache/ruact/server-functions.json") }
      let(:ts_path)   { File.join(@tmpdir, "app/javascript/.ruact/server-functions.ts") }

      def invoke!
        Rake::Task["ruact:server_functions:generate"].reenable
        Rake::Task["ruact:server_functions:generate"].invoke
      end

      it "registers the task under the documented name" do
        expect(Rake.application.lookup("ruact:server_functions:generate")).not_to be_nil
      end

      it "writes both the v2 JSON bridge and the TS module on first run", :aggregate_failures do
        invoke!
        expect(File).to exist(json_path)
        expect(File).to exist(ts_path)
        expect(JSON.parse(File.read(json_path)).fetch("version")).to eq(2)
        expect(File.read(ts_path)).to include("// AUTO-GENERATED by vite-plugin-ruact")
        expect(File.read(ts_path)).to include("_makeServerFunction({ method: \"POST\"")
      end

      it "is idempotent: a second run does not change file contents" do
        invoke!
        before = File.read(ts_path)
        invoke!
        expect(File.read(ts_path)).to eq(before)
      end

      it "exits 1 with a `[ruact] error:` line when codegen raises a ConfigurationError" do
        allow(Ruact::ServerFunctions).to receive(:write_v2_snapshot!)
          .and_raise(Ruact::ConfigurationError,
                     "server-function naming collision: PostsController#create and ...")
        expect { invoke! }
          .to raise_error(SystemExit)
          .and output(/\[ruact\] error:.*naming collision/).to_stderr
      end
    end
  end
end
