# frozen_string_literal: true

require "spec_helper"
require "rake"
require "tmpdir"
require "fileutils"

# Story 8.0a — exercises `rake ruact:server_functions:generate` end-to-end:
# the task's body runs against a tmpdir as Rails.root, stubs the
# :environment dependency, and asserts that:
#   1. The JSON bridge is written to tmp/cache/ruact/.
#   2. The TypeScript module is written to app/javascript/.ruact/.
#   3. Re-running the task is idempotent (no rewrites on unchanged registry).
#   4. ConfigurationError surfaces with a non-zero exit and a `[ruact] error:` line.
module Ruact
  module ServerFunctions
    RSpec.describe "rake ruact:server_functions:generate", :story_8_0a do
      around do |example|
        Dir.mktmpdir do |dir|
          original_root = Rails.root
          Rails.root    = Pathname.new(dir)
          @tmpdir       = dir

          prev = Rake.application
          Rake.application = Rake::Application.new
          Rake.application.define_task(Rake::Task, :environment)
          load File.expand_path("../../../lib/tasks/ruact.rake", __dir__)

          example.run
        ensure
          Rake.application = prev
          Rails.root       = original_root
        end
      end

      let(:json_path) { File.join(@tmpdir, "tmp/cache/ruact/server-functions.json") }
      let(:ts_path)   { File.join(@tmpdir, "app/javascript/.ruact/server-functions.ts") }

      def invoke!
        Rake::Task["ruact:server_functions:generate"].reenable
        Rake::Task["ruact:server_functions:generate"].invoke
      end

      it "registers the task under the documented name (Story 8.0a)" do
        expect(Rake.application.lookup("ruact:server_functions:generate")).not_to be_nil
      end

      it "writes both the JSON bridge and the TS module on first run (Story 8.0a)",
         :aggregate_failures do
        invoke!
        expect(File).to exist(json_path)
        expect(File).to exist(ts_path)
        expect(File.read(ts_path)).to include("// AUTO-GENERATED by vite-plugin-ruact")
      end

      it "is idempotent: a second run does not change file contents (Story 8.0a)" do
        invoke!
        before = File.read(ts_path)
        invoke!
        expect(File.read(ts_path)).to eq(before)
      end

      it "produces the byte-identical TS module to Codegen.render (Story 8.0a AC7)" do
        Ruact.action_registry.register(:demo_ping, kind: :action)
        invoke!

        snapshot = Snapshot.dump(Ruact.action_registry, Ruact.query_registry,
                                 now: Time.parse(JSON.parse(File.read(json_path))["generated_at"]))
        expect(File.read(ts_path)).to eq(Codegen.render(snapshot))
      end

      it "exits 1 with a `[ruact] error:` line when the registry has an invalid symbol " \
         "(Story 8.0a — rake error reporting)" do
        # Inject a bad entry by bypassing the registry's validation (the
        # naming-bridge raises on .register; we want to verify what happens
        # when an invalid entry slipped through and the task re-validates).
        allow(Snapshot).to receive(:generate!)
          .and_raise(Ruact::ConfigurationError,
                     "ruact_action / ruact_query symbol :RECALCULATE must match /^[a-z_][a-z0-9_]*$/")
        expect { invoke! }
          .to raise_error(SystemExit)
          .and output(/\[ruact\] error:.*RECALCULATE/).to_stderr
      end
    end
  end
end
